color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.712
  lightness: 1
  rhythmicContrast: 0.38967
  saturation: 0.347227
layout_spectrum: 0.24547498836182058
name: AskBetterQuestions
typography_spectrum: 0.341216
